post_upgrade()
{
	      DESKTOP_USER=$(getent passwd | awk -F: '$3 >= 1000 && $3 < 65534 {print $1}' | head -n1)
	      if [[ -n "$DESKTOP_USER" ]]; then
		   # Use systemd-run to detach from the pacman process tree and avoid killing the app when pacman finishes
		   # execution of the wrapper script which waits for the lock
		   systemd-run --unit=linexin-autostart --description="Linexin Upgrade Tool Autostart" /usr/share/linexin-upgrade-tool/autostart_wrapper.sh "$DESKTOP_USER"
	      fi
}
